services:
  arr-stack-manager:
    build: .
    container_name: arr-stack-manager
    restart: unless-stopped
    ports:
      - "5005:8000"
    # Volume komplett entfernen, damit der Container die internen Dateien nutzt
    environment:
      - TZ=Europe/Berlin
