name: Build and Publish
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/maomao63/arr-stack-manager:latest
          # Hier dein GitHub Token einfügen, damit das Repo das Image auf GHCR speichern darf
